### PR TITLE
Consulhealthchecks

### PR DESCRIPTION
**Pull request by evan4498**

### CODE REVIEW

**Comment by martinb3** [comment]
Is there intended to be a recipe in here? Just noticing that these files don't do anything by themselves. Also, just to play it safe, it might be worth ensuring python is installed.

**Comment by evan4498** [comment]
@martinb3 @Linuturk no recipe with these commits, these are simply the health checks scripts and templates to support the other PR for installing consul and configuring service checks

**Comment by evan4498** [comment]
@Linuturk can you comment on python?

**Comment by Linuturk** [comment]
As documented at the top of each python script, these python libraries and packages are required for those scripts to run properly:

```
# Requirements
# Packages:
# * python-dev
# * build-essential
# pip:
# * argparse
# * psutil
```

**Comment by prometheanfire** [comment]
does it install pip packages system wide?

**Comment by Linuturk** [comment]
Nothing in this PR does any installation at all. These are simple health check scripts and an erb template. Dependency installation will have to be handled with a recipe as part of the consul installation.

**Comment by prometheanfire** [comment]
then why does it need pip?

**Comment by Linuturk** [comment]
I was specifying the method those dependencies should be installed. Per our conversation, I'll add a requirements.txt to this PR.

**Comment by prometheanfire** [comment]
thanks, this should make what we install more consistent

**Pull request merged**
