### PR TITLE
Adding slack-handler

### PR DESCRIPTION
**Pull request by fernandohonig**
Adding slack-handler in order to help support to identify nodes failing convergence in chef.

### CODE REVIEW

**Comment by lmunro** [comment]
:+1:

**Comment by marcoamorales** [comment]
@fernandohonig please don't bump versions in a PR, or include CHANGELOG data.

**Comment by prometheanfire** [comment]
also, adding unpublished cookbooks is bad for our downstream consumers (berks info isn't propagated very well).

**Comment by jujugrrr** [comment]
> @fernandohonig please don't bump versions in a PR, or include CHANGELOG data.

Could we document the process somewhere ? Maybe it's time to update https://github.com/rackspace-cookbooks/platformstack/blob/master/CONTRIBUTING.md I'm not sure people are aware of the "Bump for dev".

> also, adding unpublished cookbooks is bad for our downstream consumers (berks info isn't propagated very well).

I do agree it's not ideal, It worth adding to the README/dependencies people should use the Berks entry if they want to use slack_handler.

**Comment by martinb3** [comment]
> Could we document the process somewhere ?

FYI, I believe it's proposed at https://github.com/AutomationSupport/devops-rfc/pull/23.

> It worth adding to the README/dependencies people should use the Berks entry if they want to use slack_handler.

I believe with this change/dependency added, _all_ customers will have to add this entry to their Berksfile, regardless of if they use slack_handler or not.

**Comment by prometheanfire** [comment]
@martinb3 you are correct, they all will need the entry if using this version.

**Comment by martinb3** [comment]
PR to fix upstream @ https://github.com/dcm-ops/chef-slack_handler/pull/6

**Pull request merged**
