### PR TITLE
hybrid uses a diferent user/api then cloud uses

### PR DESCRIPTION
**Pull request by prometheanfire**
this is needed for ticket routing purposes

### CODE REVIEW

**Comment by gondoi** [comment]
Can't we just set the attribute appropriately in the attributes file or somewhere instead of an if statement with a duplicated resource?

**Comment by prometheanfire** [comment]
this is needed because a customer could have both dedicated devices (through hybrid) and cloud devices (through cloud)

**Comment by martinb3** [comment]
I was expecting foodcritic to want you to remove the if and use only_if on each resource, but I guess it doesn't complain.

**Comment by prometheanfire** [comment]
ya, I do it this way because it's less work pragmatically / computationally.

**Comment by prometheanfire** [comment]
hello?

**Pull request merged**
