### PR TITLE
added iptables enable guard

### PR DESCRIPTION
**Pull request by cybermerc**
added iptables guard and cleaned up rubocop errors

### CODE REVIEW

**Comment by martinb3** [comment]
Hey guys -- this seems _very_ confusing. We have two recipes `::iptables` and `::acl`, but if `node['platformstack']['iptables']['enabled']` is true, it includes the `::acl` recipe?

**Comment by cybermerc** [comment]
yeah its been that way for a long time. The acl recipe is called by rackops, adding rackspace specific rules. The iptables recipe was hardwired into the default recipe, this placed a guard to allow this to be bypassed. Not sure how to clean this up further without a pretty major re-write ?

**Comment by martinb3** [comment]
I think we should revert. While some of this has been there a while, we can avoid making it worse.

**Comment by prometheanfire** [comment]
this should really be fixed in rackspace_iptables so that it has a master guard more or less.

**Pull request merged**
