### PR TITLE
Install consul

### PR DESCRIPTION
**Pull request by evan4498**

### CODE REVIEW

**Comment by martinb3** [comment]
I think this needs a new file `attributes/consul.rb`:

``` ruby
default['platformstack']['consul']['enabled'] = true
```

(can be false as well, but probably needs to default to something)

**Comment by ghost** [comment]
Neat.

**Comment by evan4498** [comment]
@martinb3 we added the default attribute as false, passing jenkins now

**Comment by martinb3** [comment]
@rstrox @evan4498 Can you also do a version bump on this? I'd think minor version since it's a new feature.

**Pull request merged**
