### PR TITLE
Issue 84 - Using platform_family to add apt::default

### PR DESCRIPTION
**Pull request by fernandohonig**

### CODE REVIEW

**Comment by gondoi** [comment]
Did foodcritic or rubocop complain about this? I would have expected it would want something like this:

``` ruby
include_recipe 'apt' if platform_family?('debian')
```

**Comment by fernandohonig** [comment]
No complaints at all :)

**Comment by gondoi** [comment]
Oh. It's because of this: https://github.com/AutomationSupport/platformstack/blob/master/.rubocop.yml#L20-L21

:disappointed:

**Comment by fernandohonig** [comment]
Changed if statement

**Pull request merged**
