### PR TITLE
use ruby net/http instead of rest_client lib for public_info plugin

### PR DESCRIPTION
**Pull request by jarosser06**

### CODE REVIEW

**Comment by prometheanfire** [comment]
:+1:

where's the ci testing though :|

**Comment by martinb3** [comment]
Looking into why CI didn't run. Probably has something to do with the fork the code came from, maybe not whitelisted.

**Comment by martinb3** [comment]
Pushed the same code to a branch under rackspace-cookbooks: https://github.com/rackspace-cookbooks/platformstack/tree/rest_client

This appears to have initiated tests.

**Comment by martinb3** [comment]
Looks good to me. Converge and verify passed.

**Comment by jujugrrr** [comment]
If we do this we should remove rest-client there https://github.com/the-galley/platformstack/blob/remove_rest_client/recipes/public_info.rb#L12-L14.

Meaning rackspace_cloudbackup should be fixed

**Comment by martinb3** [comment]
Filed a PR to add the dependency to the other cookbook. https://github.com/rackspace-cookbooks/rackspace_cloudbackup/pull/23.

**Pull request merged**
