### PR TITLE
Support LXC/Docker, for testing

### PR DESCRIPTION
**Pull request by martinb3**
Would need to resolve https://github.com/sethvargo/chef-sugar/issues/60 and/or https://github.com/rackerlabs/ohai-plugins/issues/121. These would let us do guards like `node.lxc?` based on the values inside `node['virtualization']`, but they are currently not being populated.

### CODE REVIEW

**Comment by martinb3** [comment]
If it sped us up 400%, I think it'd be worth it. It would be a drop in replacement for vagrant, which isn't like our cloud images for ubuntu or centos either.

**Comment by prometheanfire** [comment]
as long as we still have to have it pass jenkins (aka, run with our cloud images), then it's ok

**Comment by martinb3** [comment]
Completely agree :)

**Comment by prometheanfire** [comment]
node['virtualization']['system'] is not going to exist everywhere, which is why I used deep fetch :P  same with node['virtualization']

**Comment by martinb3** [comment]
We would switch to `node#lxc?` from chef-sugar shortly anyway (as soon as he releases a new version, the code is already in Github). This was taken directly from that. Also, please go back to my very first comment in this issue, about needing to run the virtualization plugin in ohai before this will work.

**Comment by prometheanfire** [comment]
right

**Pull request merged**
